# These are supported funding model platforms

github: # [kivanio] # up to 4 GitHub Sponsors-enabled usernames
patreon: kivanio
open_collective:
ko_fi: kivanio
tidelift: # platform-name/package-name, e.g. rubygems/brcobranca
custom: ['https://www.paypal.me/kivanio']
