require:
  - rubocop-performance
  - "test_prof/rubocop"
  - rubocop-rspec
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 150
  AllowedPatterns: ['\A#']

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 50

Metrics/ModuleLength:
  Exclude:
    - "lib/brcobranca/boleto/template/*.rb"
