# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brcobranca}
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kivanio Barbosa"]
  s.date = %q{2010-09-21}
  s.description = %q{Gem para emissão de bloquetos de cobrança de bancos brasileiros.}
  s.email = %q{kivanio@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/brcobranca.rb",
     "lib/brcobranca/arquivos/logos/bancobrasil.jpg",
     "lib/brcobranca/arquivos/logos/banespa.jpg",
     "lib/brcobranca/arquivos/logos/bradesco.jpg",
     "lib/brcobranca/arquivos/logos/hsbc.jpg",
     "lib/brcobranca/arquivos/logos/itau.jpg",
     "lib/brcobranca/arquivos/logos/real.jpg",
     "lib/brcobranca/arquivos/logos/unibanco.jpg",
     "lib/brcobranca/arquivos/templates/modelo_generico.eps",
     "lib/brcobranca/boleto/banco_brasil.rb",
     "lib/brcobranca/boleto/banespa.rb",
     "lib/brcobranca/boleto/base.rb",
     "lib/brcobranca/boleto/bradesco.rb",
     "lib/brcobranca/boleto/hsbc.rb",
     "lib/brcobranca/boleto/itau.rb",
     "lib/brcobranca/boleto/real.rb",
     "lib/brcobranca/boleto/template/base.rb",
     "lib/brcobranca/boleto/template/rghost.rb",
     "lib/brcobranca/boleto/unibanco.rb",
     "lib/brcobranca/calculo.rb",
     "lib/brcobranca/calculo_data.rb",
     "lib/brcobranca/currency.rb",
     "lib/brcobranca/formatacao.rb",
     "lib/brcobranca/limpeza.rb",
     "lib/brcobranca/retorno/base.rb",
     "lib/brcobranca/retorno/retorno_cbr643.rb",
     "spec/arquivos/CBR64310.RET",
     "spec/brcobranca/banco_banespa_spec.rb",
     "spec/brcobranca/banco_bradesco_spec.rb",
     "spec/brcobranca/banco_brasil_spec.rb",
     "spec/brcobranca/banco_hsbc_spec.rb",
     "spec/brcobranca/banco_real_spec.rb",
     "spec/brcobranca/banco_unibanco_spec.rb",
     "spec/brcobranca/base_spec.rb",
     "spec/brcobranca/core_ext_spec.rb",
     "spec/brcobranca/currency_spec.rb",
     "spec/brcobranca/itau_spec.rb",
     "spec/brcobranca/retorno_cbr643_spec.rb",
     "spec/brcobranca/rghost_spec.rb",
     "spec/brcobranca_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kivanio/brcobranca}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["GhostScript > 8.0, para gear PDF e c\303\263digo de Barras"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Gem que permite trabalhar com bloquetos de cobrança para bancos brasileiros.}
  s.test_files = [
    "spec/brcobranca/banco_banespa_spec.rb",
     "spec/brcobranca/banco_bradesco_spec.rb",
     "spec/brcobranca/banco_brasil_spec.rb",
     "spec/brcobranca/banco_hsbc_spec.rb",
     "spec/brcobranca/banco_real_spec.rb",
     "spec/brcobranca/banco_unibanco_spec.rb",
     "spec/brcobranca/base_spec.rb",
     "spec/brcobranca/core_ext_spec.rb",
     "spec/brcobranca/currency_spec.rb",
     "spec/brcobranca/itau_spec.rb",
     "spec/brcobranca/retorno_cbr643_spec.rb",
     "spec/brcobranca/rghost_spec.rb",
     "spec/brcobranca_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rghost>, [">= 0.8.7"])
      s.add_runtime_dependency(%q<rghost_barcode>, [">= 0.8"])
      s.add_runtime_dependency(%q<parseline>, [">= 1.0.3"])
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rghost>, [">= 0.8.7"])
      s.add_dependency(%q<rghost_barcode>, [">= 0.8"])
      s.add_dependency(%q<parseline>, [">= 1.0.3"])
      s.add_dependency(%q<activemodel>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rghost>, [">= 0.8.7"])
    s.add_dependency(%q<rghost_barcode>, [">= 0.8"])
    s.add_dependency(%q<parseline>, [">= 1.0.3"])
    s.add_dependency(%q<activemodel>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

