# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brcobranca}
  s.version = "2.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kivanio Barbosa"]
  s.date = %q{2010-05-14}
  s.description = %q{Gem para emissão de bloquetos de cobrança de bancos brasileiros.}
  s.email = %q{kivanio@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/brcobranca.feature",
     "features/step_definitions/brcobranca_steps.rb",
     "features/support/env.rb",
     "lib/brcobranca.rb",
     "spec/brcobranca_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kivanio/brcobranca}
  s.rdoc_options = ["--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{brcobranca}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Gem que permite trabalhar com bloquetos de cobrança para bancos brasileiros.}
  s.test_files = [
    "spec/brcobranca/banco_banespa_spec.rb",
     "spec/brcobranca/banco_bradesco_spec.rb",
     "spec/brcobranca/banco_brasil_spec.rb",
     "spec/brcobranca/banco_hsbc_spec.rb",
     "spec/brcobranca/banco_itau_spec.rb",
     "spec/brcobranca/banco_real_spec.rb",
     "spec/brcobranca/banco_unibanco_spec.rb",
     "spec/brcobranca/base_spec.rb",
     "spec/brcobranca/core_ext_spec.rb",
     "spec/brcobranca/currency_spec.rb",
     "spec/brcobranca/retorno_cbr643_spec.rb",
     "spec/brcobranca/rghost_spec.rb",
     "spec/brcobranca/template/rghost_spec.rb",
     "spec/brcobranca/template/util_spec.rb",
     "spec/brcobranca_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rghost>, [">= 0.8.7"])
      s.add_runtime_dependency(%q<rghost_barcode>, [">= 0.8"])
      s.add_runtime_dependency(%q<parseline>, [">= 1.0.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rghost>, [">= 0.8.7"])
      s.add_dependency(%q<rghost_barcode>, [">= 0.8"])
      s.add_dependency(%q<parseline>, [">= 1.0.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rghost>, [">= 0.8.7"])
    s.add_dependency(%q<rghost_barcode>, [">= 0.8"])
    s.add_dependency(%q<parseline>, [">= 1.0.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

